- name: Get nodes ips
  command: "oc get nodes  -o jsonpath='{.items[*].status.addresses[?(@.type==\"InternalIP\")].address}'"
  register: ocp_nodes_out

- name: Get nodes names
  command: "oc get nodes  -o jsonpath='{.items[*].metadata.name}'"
  register: ocp_nodes_names_out

- name: Debug nodes results
  debug:
    msg: "{{ ocp_nodes_out }}"

- name: set nodes as fact
  set_fact:
    ocp_nodes_ips: "{{ ocp_nodes_out.stdout.split(' ') }}"
    ocp_nodes_names: "{{ ocp_nodes_names_out.stdout.split(' ') }}"
